### ISSUE TITLE
Upgrade symfony/yaml requirement

### ISSUE THREAD

**Issue by lukaszjankowski** [yalesov/php-yaml#1]
Any chances to upgrade symfony/yaml requirement?

Current requirement is "symfony/yaml": "2.0.*", it would be nice to have e.g. "symfony/yaml": "2.*"

Version 2.0.* is a little outdated and conflicts with other vendors requirements.

**Comment by joeswann** [comment]
+1

**Comment by rickhewes** [comment]
+1

**Comment by Olly667** [comment]
+1

**Comment by yalesov** [comment]
fixed in master, requirement is now `*`
